// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbCursos = new HashSet<tbCursos>();
        }

        public int Cat_Id { get; set; }
        public string Cat_Nombre { get; set; }
        public int Cat_UsuarioCreacion { get; set; }
        public DateTime Cat_FechaCreacion { get; set; }
        public int? Cat_UsuarioModificacion { get; set; }
        public DateTime? Cat_FechaModificacion { get; set; }
        public bool? Cat_Estado { get; set; }

        public virtual tbUsuarios Cat_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Cat_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursos { get; set; }
    }
}