// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbInstructores = new HashSet<tbInstructores>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Est_Id { get; set; }
        public string Est_Descripcion { get; set; }
        public int Est_UsuarioCreacion { get; set; }
        public DateTime Est_FechaCreacion { get; set; }
        public int? Est_UsuarioModificacion { get; set; }
        public DateTime? Est_FechaModificacion { get; set; }
        public bool? Est_Estado { get; set; }

        public virtual tbUsuarios Est_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Est_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInstructores> tbInstructores { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}