// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbInstructores
    {
        public tbInstructores()
        {
            tbInstructoresPorCurso = new HashSet<tbInstructoresPorCurso>();
        }

        public int Ins_Id { get; set; }
        public string Ins_Nombre { get; set; }
        public string Ins_Apellido { get; set; }
        public DateTime Ins_FechaNacimiento { get; set; }
        public string Ins_Sexo { get; set; }
        public int Est_Id { get; set; }
        public string Ins_Direccion { get; set; }
        public string Mun_Id { get; set; }
        public string Ins_Telefono { get; set; }
        public string Ins_CorreoElectronico { get; set; }
        public int? Ins_UsuarioCreacion { get; set; }
        public DateTime? Ins_FechaCreacion { get; set; }
        public int? Ins_UsuarioModificacion { get; set; }
        public DateTime? Ins_FechaModificacion { get; set; }
        public bool? Ins_Estado { get; set; }

        public virtual tbEstadosCiviles Est { get; set; }
        public virtual tbUsuarios Ins_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Ins_UsuarioModificacionNavigation { get; set; }
        public virtual tbMunicipios Mun { get; set; }
        public virtual ICollection<tbInstructoresPorCurso> tbInstructoresPorCurso { get; set; }
    }
}