// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbInstructoresPorCurso
    {
        public int IpC_Id { get; set; }
        public int Ins_Id { get; set; }
        public int Cur_Id { get; set; }
        public int IpC_UsuarioCreacion { get; set; }
        public DateTime IpC_FechaCreacion { get; set; }
        public int? IpC_UsuarioModificacion { get; set; }
        public DateTime? IpC_FechaModificacion { get; set; }
        public bool? IpC_Estado { get; set; }

        public virtual tbCursos Cur { get; set; }
        public virtual tbInstructores Ins { get; set; }
        public virtual tbUsuarios IpC_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios IpC_UsuarioModificacionNavigation { get; set; }
    }
}