// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbInfoPagos
    {
        public int Inp_Id { get; set; }
        public string Inp_Descripcion { get; set; }
        public int? Usu_Id { get; set; }
        public int? Mtp_Id { get; set; }
        public int? Inp_UsuarioCreacion { get; set; }
        public DateTime? Inp_FechaCreacion { get; set; }
        public int? Inp_UsuarioModificacion { get; set; }
        public DateTime? Inp_FechaModificacion { get; set; }
        public bool? Inp_Estado { get; set; }

        public virtual tbUsuarios Inp_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Inp_UsuarioModificacionNavigation { get; set; }
        public virtual tbMetodosPagos Mtp { get; set; }
        public virtual tbUsuarios Usu { get; set; }
    }
}