// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbMetodosPagos
    {
        public tbMetodosPagos()
        {
            tbInfoPagos = new HashSet<tbInfoPagos>();
        }

        public int Mtp_Id { get; set; }
        public string Mtp_Descripcion { get; set; }
        public int? Mtp_UsuarioCreacion { get; set; }
        public DateTime? Mtp_FechaCreacion { get; set; }
        public int? Mtp_UsuarioModificacion { get; set; }
        public DateTime? Mtp_FechaModificacion { get; set; }
        public bool? Mtp_Estado { get; set; }

        public virtual tbUsuarios Mtp_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Mtp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInfoPagos> tbInfoPagos { get; set; }
    }
}