// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbPantallasPorRoles = new HashSet<tbPantallasPorRoles>();
        }

        public int Pan_Id { get; set; }
        public string Pan_Descripcion { get; set; }
        public int? Pan_UsuarioCreacion { get; set; }
        public DateTime? Pan_FechaCreacion { get; set; }
        public int? Pan_UsuarioModificacion { get; set; }
        public DateTime? Pan_FechaModificacion { get; set; }
        public bool? Pan_Estado { get; set; }

        public virtual tbUsuarios Pan_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Pan_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
    }
}