// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int Ppr_Id { get; set; }
        public int? Pan_Id { get; set; }
        public int? Rol_Id { get; set; }
        public int? Ppr_UsuarioCreacion { get; set; }
        public DateTime? Ppr_FechaCreacion { get; set; }
        public int? Ppr_UsuarioModificacion { get; set; }
        public DateTime? Ppr_FechaModificacion { get; set; }
        public bool? Ppr_Estado { get; set; }

        public virtual tbPantallas Pan { get; set; }
        public virtual tbUsuarios Ppr_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Ppr_UsuarioModificacionNavigation { get; set; }
        public virtual tbRoles Rol { get; set; }
    }
}