// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbPantallasPorRoles = new HashSet<tbPantallasPorRoles>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Rol_Id { get; set; }
        public string Rol_Descripcion { get; set; }
        public int? Rol_UsuarioCreacion { get; set; }
        public int? Rol_UsuarioModificacion { get; set; }
        public DateTime? Rol_FechaCreacion { get; set; }
        public DateTime? Rol_FechaModificacion { get; set; }
        public bool? Rol_Estado { get; set; }

        public virtual tbUsuarios Rol_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Rol_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}