// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aplicacion_CursosJD.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsu_UsuarioCreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsu_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbCategoriasCat_UsuarioCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriasCat_UsuarioModificacionNavigation = new HashSet<tbCategorias>();
            tbCursosCur_UsuarioCreacionNavigation = new HashSet<tbCursos>();
            tbCursosCur_UsuarioModificacionNavigation = new HashSet<tbCursos>();
            tbCusrsosPorUsuarioCpU_UsuarioCreacionNavigation = new HashSet<tbCusrsosPorUsuario>();
            tbCusrsosPorUsuarioCpU_UsuarioModificacionNavigation = new HashSet<tbCusrsosPorUsuario>();
            tbCusrsosPorUsuarioUsu = new HashSet<tbCusrsosPorUsuario>();
            tbDepartamentosDep_UsuarioCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosDep_UsuarioModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEstadosCivilesEst_UsuarioCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEst_UsuarioModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbInfoPagosInp_UsuarioCreacionNavigation = new HashSet<tbInfoPagos>();
            tbInfoPagosInp_UsuarioModificacionNavigation = new HashSet<tbInfoPagos>();
            tbInfoPagosUsu = new HashSet<tbInfoPagos>();
            tbInstructoresIns_UsuarioCreacionNavigation = new HashSet<tbInstructores>();
            tbInstructoresIns_UsuarioModificacionNavigation = new HashSet<tbInstructores>();
            tbInstructoresPorCursoIpC_UsuarioCreacionNavigation = new HashSet<tbInstructoresPorCurso>();
            tbInstructoresPorCursoIpC_UsuarioModificacionNavigation = new HashSet<tbInstructoresPorCurso>();
            tbMetodosPagosMtp_UsuarioCreacionNavigation = new HashSet<tbMetodosPagos>();
            tbMetodosPagosMtp_UsuarioModificacionNavigation = new HashSet<tbMetodosPagos>();
            tbMunicipiosMun_UsuarioCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosMun_UsuarioModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasPan_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPan_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPpr_UsuarioCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPpr_UsuarioModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbRecursosRec_UsuarioCreacionNavigation = new HashSet<tbRecursos>();
            tbRecursosRec_UsuarioModificacionNavigation = new HashSet<tbRecursos>();
            tbRolesRol_UsuarioCreacionNavigation = new HashSet<tbRoles>();
            tbRolesRol_UsuarioModificacionNavigation = new HashSet<tbRoles>();
            tbTiposRecursosTpR_UsuarioCreacionNavigation = new HashSet<tbTiposRecursos>();
            tbTiposRecursosTpR_UsuarioModificacionNavigation = new HashSet<tbTiposRecursos>();
        }

        public int Usu_Id { get; set; }
        public string Usu_Usuario { get; set; }
        public string Usu_Contrasena { get; set; }
        public string Usu_Nombre { get; set; }
        public string Usu_Apellido { get; set; }
        public DateTime? Usu_FechaNacimiento { get; set; }
        public string Usu_Sexo { get; set; }
        public string Usu_Direccion { get; set; }
        public string Usu_Telefono { get; set; }
        public string Usu_CorreoElectronico { get; set; }
        public int? Est_Id { get; set; }
        public int? Rol_Id { get; set; }
        public string Mun_Id { get; set; }
        public bool? Usu_Admin { get; set; }
        public int? Usu_UsuarioCreacion { get; set; }
        public DateTime? Usu_FechaCreacion { get; set; }
        public int? Usu_UsuarioModificacion { get; set; }
        public DateTime? Usu_FechaModificacion { get; set; }
        public bool? Usu_Estado { get; set; }

        public virtual tbEstadosCiviles Est { get; set; }
        public virtual tbMunicipios Mun { get; set; }
        public virtual tbRoles Rol { get; set; }
        public virtual tbUsuarios Usu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Usu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasCat_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasCat_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursosCur_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursosCur_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCusrsosPorUsuario> tbCusrsosPorUsuarioCpU_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbCusrsosPorUsuario> tbCusrsosPorUsuarioCpU_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCusrsosPorUsuario> tbCusrsosPorUsuarioUsu { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosDep_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosDep_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEst_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEst_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInfoPagos> tbInfoPagosInp_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbInfoPagos> tbInfoPagosInp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInfoPagos> tbInfoPagosUsu { get; set; }
        public virtual ICollection<tbInstructores> tbInstructoresIns_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbInstructores> tbInstructoresIns_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbInstructoresPorCurso> tbInstructoresPorCursoIpC_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbInstructoresPorCurso> tbInstructoresPorCursoIpC_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPagos> tbMetodosPagosMtp_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPagos> tbMetodosPagosMtp_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosMun_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosMun_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPan_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPan_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPpr_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPpr_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRecursos> tbRecursosRec_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRecursos> tbRecursosRec_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposRecursos> tbTiposRecursosTpR_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbTiposRecursos> tbTiposRecursosTpR_UsuarioModificacionNavigation { get; set; }
    }
}